Mv: use realpath(1); allow to move to directory; use Write
Paths are now cleaned via realpath(1), e.g.
'realpath /tmp/baz/foo/../../bar'.

Mv foo/bar/ will move the current file to foo/bar/<filename>.

Direct calls to 9p(1) have been replace by Write.

diff --git a/bin/Mv b/bin/Mv
--- a/bin/Mv
+++ b/bin/Mv
@@ -14,17 +14,25 @@ SYNOPSYS
 
 DESCRIPTION
 	Move (mv(1)) current file, or the one pointed by [-a|id|pattern],
-	to the new one, updating acme's buffer's name accordingly.
+	to a new one, on the filesystem that is, and updating acme's
+	buffer's name accordingly.
 
-	If to doesn't start with a leading '/', renaming is performed
+	If 'to' doesn't start with a leading '/', renaming is performed
 	relatively instead of absolutely.
 
-	If to describes a missing path, intermediate directories
+	If the current buffer points to a file (by opposition to a directory),
+	and 'to' ends with a '/', then the file pointed by the current buffer
+	is moved to the directory pointed by 'to'.
+
+	If 'to' describes a missing path, intermediate directories
 	are created (mkdir(1) -p); existing file is overwritten,
 	following mv(1)' semantic.
 
 EXAMPLE
-	Rename from "/home/foo/bar.c" to "/home/foo/baz.c":
+	In each of the example below, the source filename is
+	to be interpreted as the current buffer's name.
+
+	Renaming "/home/foo/bar.c" to "/home/foo/baz.c":
 		Mv /home/foo/baz.c
 		Mv baz.c
 
@@ -32,9 +40,18 @@ EXAMPLE
 		Mv foo
 		Mv foo/
 
+	Renaming "foo.c" to "foo/bar/foo.c":
+		Mv foo/bar/
+
+	Renaming "foo.c" to "foo/bar":
+		Mv foo/bar
+
 BUGS:
 	We may want to allow regexp(7) with capture, so as to allow
 	renaming multiple files/buffers at once.
+
+	We require realpath(1) to be available to clean up the path,
+	e.g. in case of 'Mv ../../'.
 
 EOF
 	exit 0
@@ -42,6 +59,12 @@ fi
 
 if [ -z "$1" ]; then
 	echo `basename $0` '<to> [-a|id|pattern]' >&2
+	exit 1
+fi
+
+if ! which realpath >/dev/null; then
+	# seems standard enough
+	echo 'realpath(1) not found' 1>&2
 	exit 1
 fi
 
@@ -57,8 +80,15 @@ Getids $2 | sed 1q | while read x; do
 
 	mkdir -p `dirname $to`
 
+	if [ -f "$y" ] && echo "$to" | grep -q '/$'; then
+		mkdir -p $to
+		to=$to`basename $y`
+	fi
+
+	to=`realpath $to`
+
 	if [ -e "$y" ]; then mv "$y" "$to"; fi
 
-	echo "name $to" | 9p write acme/$x/ctl
-	echo get | 9p write acme/$x/ctl
+	Write ctl "name $to\n" $x
+	Write ctl get          $x
 done
